@Webhook.API_HostAddress = http://localhost:5041


### Create fine
POST {{Webhook.API_HostAddress}}/fines
Content-Type: application/json
{
  "clientId": "Raizen",
  "driverName": "João da Silva{{$randomInt}}",
  "amount": {{$randomInt}}
}

### Create subscription
POST {{Webhook.API_HostAddress}}/webhooks/subscriptions
Content-Type: application/json
{
  "eventType": "fine.created",
  "clientId": "Raizen",
  "webhookUrl": "https://webhook.site/ed2ffc0a-41ef-4216-a443-6a95897b795c"
}